add avx to runners

diff --git a/.github/workflows/reusable_run_test_and_examples_by_linking_type.yml b/.github/workflows/reusable_run_test_and_examples_by_linking_type.yml
--- a/.github/workflows/reusable_run_test_and_examples_by_linking_type.yml
+++ b/.github/workflows/reusable_run_test_and_examples_by_linking_type.yml
@@ -19,6 +19,8 @@ on:
         type: boolean
       with-Werror:
         type: boolean
+      with-AVX:
+        type: boolean
     secrets:
       coverall-token:
         description: 'Access token for coverall. Required if inputs.with-coverage'
@@ -26,7 +28,7 @@ on:
 
 jobs:
   tests-and-examples:
-    name: ${{ fromJSON('["static", "shared"]')[inputs.build-shared-libs] }} lib${{ fromJSON('["", " + sanitizers"]')[inputs.with-sanitizer] }}${{ fromJSON('["", " + code coverage"]')[inputs.with-coverage] }}
+    name: ${{ fromJSON('["static", "shared"]')[inputs.build-shared-libs] }} lib${{ fromJSON('["", " + sanitizers"]')[inputs.with-sanitizer] }}${{ fromJSON('["", " + code coverage"]')[inputs.with-coverage] }}${{ fromJSON('["", " + AVX"]')[inputs.with-AVX] }}
     runs-on: ${{ inputs.os }}
     defaults:
       run:
@@ -59,6 +61,20 @@ jobs:
       - name: use mold as default linker
         uses: rui314/setup-mold@v1
 
+      - name: Check AVX
+        env:
+          CC: ${{ steps.install_cc.outputs.cc }}
+          CXX: ${{ steps.install_cc.outputs.cxx }}
+        run: |
+          echo 'int main() { return __AVX2__; }' > /tmp/rdf4cpp-avx-test.cpp
+          AVX_RET=$(${CXX} ${{ fromJSON('["", "-march=native"]')[inputs.with-AVX] }} -o /dev/null /tmp/rdf4cpp-avx-test.cpp; echo $?)
+          
+          # Shell: true=zero-exit, false=non-zero-exit
+          AVX_EXISTS=$(test $AVX_RET -eq 0)
+          AVX_SHOUD_EXIST=${{ fromJSON('["1", "0"]')[inputs.with-AVX] }}
+          
+          test $AVX_EXISTS -eq $AVX_SHOULD_EXIST
+
       - name: Configure conan
         run: |
           pip3 install "conan==1.60.1" ${{ fromJSON('["", "gcovr"]')[inputs.with-coverage] }}
@@ -80,7 +96,7 @@ jobs:
         env:
           CC: ${{ steps.install_cc.outputs.cc }}
           CXX: ${{ steps.install_cc.outputs.cxx }}
-          CXXFLAGS: -Wno-unused-command-line-argument -fuse-ld=mold ${{ fromJSON('["", "-fsanitize=undefined -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls"]')[inputs.with-sanitizer] }} ${{ fromJSON('["", "--coverage"]')[inputs.with-coverage] }} ${{ fromJSON('["", "-Werror"]')[inputs.with-Werror] }}
+          CXXFLAGS: -Wno-unused-command-line-argument -fuse-ld=mold ${{ fromJSON('["", "-fsanitize=undefined -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls"]')[inputs.with-sanitizer] }} ${{ fromJSON('["", "--coverage"]')[inputs.with-coverage] }} ${{ fromJSON('["", "-Werror"]')[inputs.with-Werror] }} ${{ fromJSON('["", "-march=native"]')[inputs.with-AVX] }}
         run: >
           cmake -G Ninja -B build_dir -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON
           ${{ fromJSON('["", "-DBUILD_SHARED_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON"]')[inputs.build-shared-libs] }}
